// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzSPU_gFKZHHYjXDIGs5Byn8GZw5FjVMc',
    appId: '1:376711198932:web:8b03004865315659cd2341',
    messagingSenderId: '376711198932',
    projectId: 'editflow-editorsworkspace',
    authDomain: 'editflow-editorsworkspace.firebaseapp.com',
    storageBucket: 'editflow-editorsworkspace.firebasestorage.app',
    measurementId: 'G-WE6733C167',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfxLsphWR_Zs6n2dQHfx11mpD4ulplq6E',
    appId: '1:376711198932:android:21c51834243adec5cd2341',
    messagingSenderId: '376711198932',
    projectId: 'editflow-editorsworkspace',
    storageBucket: 'editflow-editorsworkspace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhaqhP0LDFFMpHhfPD0VS9ztKc6A5RcRY',
    appId: '1:376711198932:ios:dbb2c474c349650bcd2341',
    messagingSenderId: '376711198932',
    projectId: 'editflow-editorsworkspace',
    storageBucket: 'editflow-editorsworkspace.firebasestorage.app',
    iosBundleId: 'com.editflow.editflow',
  );
}
